//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCCWebBrowser {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class PublicSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PublicSettings defaultInstance = ((PublicSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PublicSettings())));
        
        public static PublicSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PubilcPassword {
            get {
                return ((string)(this["PubilcPassword"]));
            }
            set {
                this["PubilcPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PubilcTakeCount {
            get {
                return ((string)(this["PubilcTakeCount"]));
            }
            set {
                this["PubilcTakeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PubilcTimerElapse {
            get {
                return ((string)(this["PubilcTimerElapse"]));
            }
            set {
                this["PubilcTimerElapse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PubilcUserName {
            get {
                return ((string)(this["PubilcUserName"]));
            }
            set {
                this["PubilcUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicProxyUid {
            get {
                return ((string)(this["PublicProxyUid"]));
            }
            set {
                this["PublicProxyUid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicProxyPwd {
            get {
                return ((string)(this["PublicProxyPwd"]));
            }
            set {
                this["PublicProxyPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PublicPort {
            get {
                return ((int)(this["PublicPort"]));
            }
            set {
                this["PublicPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicDBName {
            get {
                return ((string)(this["PublicDBName"]));
            }
            set {
                this["PublicDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PublicHasDBPassword {
            get {
                return ((bool)(this["PublicHasDBPassword"]));
            }
            set {
                this["PublicHasDBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PublicRegBegin {
            get {
                return ((string)(this["PublicRegBegin"]));
            }
            set {
                this["PublicRegBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicRegEnd {
            get {
                return ((string)(this["PublicRegEnd"]));
            }
            set {
                this["PublicRegEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicDataTable {
            get {
                return ((string)(this["PublicDataTable"]));
            }
            set {
                this["PublicDataTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicDeviceAccountDataTable {
            get {
                return ((string)(this["PublicDeviceAccountDataTable"]));
            }
            set {
                this["PublicDeviceAccountDataTable"] = value;
            }
        }
    }
}
